#!/bin/sh

## -------------------------------------------------------------------
##
## tfe-push-config: Use the Terraform Enteprise API to push a
##                  configuration into a TFE environment and start a
##                  run / plan.
##
## -------------------------------------------------------------------
##
## Copyright (c) 2018 Brent W. Woodruff.  All Rights Reserved.
##
## This file is provided to you under the Mozilla Public License
## Version 2.0 (the "License"); you may not use this file
## except in compliance with the License.  You may obtain
## a copy of the License at
##
##   https://www.mozilla.org/en-US/MPL/2.0/
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
## -------------------------------------------------------------------

###
### Function declarations
###

echoerr () { echo "$@" 1>&2; }

echodebug () {
    if [ -n "$TF_LOG" ]; then
        echoerr
        echoerr "$@"
        echoerr
    fi
}

cleanup () {
    if [ -f "$config_payload" ]; then
        echodebug "[DEBUG] Deleting temporary content file"
        rm "$config_payload" 
        if [ 0 -ne $? ]; then
            echoerr "Error deleting temporary configuration payload file:"
            echoerr "$config_payload"
        fi
    else
        echodebug "[DEBUG] No temporary content file to delete"
    fi
}

assign_arg () {
    if [ "${2#-}" != "$2" ]; then
        echoerr "Parameter $1 is missing a value"
        exit 1
    else
        echo $2
    fi
}

tfe_api_call () {
    curl $curl_silent \
         --header "Authorization: Bearer $token" \
         --header "Content-Type: application/vnd.api+json" \
         $@
}

usage () {
cat << 'EOF'
Usage:

  tfe-push-config -name [USER_OR_ORG]/[WORKSPACE] [OPTIONS] [CONFIG_DIR]

  Upload a Terraform configuration to a Terraform Enterprise workspace
  and begin a run.

Options:

  -name <name>         This parameter is required. Name of the configuration
                       in Atlas. Format is: "username_or_org/workspace".

  -tfe-address <url>   An alternate address to an Atlas instance. Defaults
                       to https://atlas.hashicorp.com

  -upload-modules true If true (default), then the modules are locked at
                       their current checkout and uploaded completely. This
                       prevents Atlas from running "terraform get".

  -token <token>       Access token to use to upload. If blank or unspecified,
                       the ATLAS_TOKEN environment variable will be used.

  -poll <seconds>      Number of seconds to wait between polling the submitted
                       run for a non-active status. Defaults to 0 (no polling).

Notes:

  The curl and jq commands are required.

EOF
exit
}

if [ -z "$(command -v jq)" ]; then
    echoerr "The jq command must be installed"
    exit 1
fi

if [ -z "$(command -v curl)" ]; then
    echoerr "The curl command must be installed"
    exit 1
fi

if [ -z "$TMPDIR" ]; then
    TMPDIR=/tmp
fi

tfe_address=https://atlas.hashicorp.com
name=
token=
config_dir=.
tar_verbose=
tar_exclude="--exclude .git"
curl_silent="-s"
poll_run=0

###
### Parse options
###

while [ -n "$1" ]; do
    case "$1" in
        help|-h|-help|--help)
            usage
            ;;
        -tfe-address)
            tfe_address=$(assign_arg "$1" "$2")
            ;;
        -upload-modules)
            case "$2" in
                true)
                    tar_exclude="--exclude .git"
                    ;;
                false)
                    tar_exclude="--exclude .git --exclude .terraform" 
                    ;;
                *)
                    echoerr "-upload-modules should be true or false"
                    exit 1
                    ;;
            esac
            ;;
        -poll)
            if [ "$2" -eq "$2" ] >/dev/null 2>&1; then
                poll_run=$(assign_arg "$1" "$2")
            else
                echoerr "-poll must be an integer"
                exit 1
            fi
            ;;
        -name)
            name=$(assign_arg "$1" "$2")
            ;;
        -token)
            token=$(assign_arg "$1" "$2")
            ;;
        *)
            # Shouldn't get here until the last option, the optional
            # config directory
            if [ $# -gt 1 ]; then
                echoerr "Trailing options following config directory $1"
                exit 1
            fi

            config_dir=$1
            ;;
    esac
    shift
    shift
done

if [ -z "$name" ]; then
    echoerr "-name is a required parameter"
    exit 1
else
    org="${name%/*}"
    workspace="${name#*/}"
fi

if [ -z "$token" ]; then
    token="$ATLAS_TOKEN"
    if [ -z "$token" ]; then
        echoerr 'Set the API token with -token or $ATLAS_TOKEN'
    fi
fi

if [ -n "$TF_LOG" ]; then
    tar_verbose=v
    curl_silent=
fi

echodebug "[DEBUG] Requesting workspace information for $org/$workspace"

# Gets the workspace ID given the organization name and workspace name
url="$tfe_address/api/v2/organizations/$org/workspaces/$workspace"
workspace_id_resp="$(tfe_api_call "$url")"
if [ 0 -ne $? ]; then
    echoerr "Error requesting workspace ID"
    cleanup
    exit 1
fi

echodebug "[DEBUG] Workspace ID response:"
echodebug "$(echo "$workspace_id_resp" | jq '')"

workspace_id="$(echo "$workspace_id_resp" | jq -r '.data.id')"
if [ 0 -ne $? ]; then
    echoerr "Error parsing API response for workspace ID"
    cleanup
    exit 1
fi

if [ -z "$workspace_id" ]; then
    echoerr "Error retrieving workspace ID. Parsing result was empty."
    cleanup
    exit 1
fi

echodebug "[DEBUG] Workspace ID: $workspace_id"

echo "Uploading Terraform configuration..."

echodebug "[DEBUG] Creating file for upload"

# Creates a tar.gz of the director with the configuration
config_payload="$TMPDIR/content-$(date +%s).tar.gz"

tar $tar_exclude -C "$config_dir" -${tar_verbose}zcf "$config_payload" .
if [ 0 -ne $? ]; then
    echoerr "Error creating archive for configuration payload"
    exit 1
fi

echodebug "[DEBUG] Creating a new configuration version for $workspace"

# The JSON Payload used to create the new cnofiguration version
config_ver_payload='{"data":{"type":"configuration-version"}}'

echodebug "[DEBUG] Requesting config versions information for $workspace_id"

# Creates the configuration version and extractes the upload-url
url=$tfe_address/api/v2/workspaces/$workspace_id/configuration-versions
upload_url_resp="$(tfe_api_call -d "$config_ver_payload" $url)"
if [ 0 -ne $? ]; then
    echoerr "Error creating configuration version"
    cleanup
    exit 1
fi

echodebug "[DEBUG] Upload URL response:" 
echodebug "$(echo "$upload_url_resp" | jq '')"

config_id="$(echo "$upload_url_resp" | jq -r '.data.id')"
url="$(echo "$upload_url_resp" | jq -r '.data.attributes."upload-url"')"
if [ 0 -ne $? ]; then
    echoerr "Error parsing API response for configuration upload"
    cleanup
    exit 1
fi

echodebug "[DEBUG] Upload URL: $url"

echodebug "[DEBUG] Uploading content to upload URL"

upload_config_resp="$(curl $curl_silent -X PUT --data-binary "@$config_payload" ${url})"
if [ 0 -ne $? ]; then
    echoerr "Error uploading configuration archive"
    cleanup
    exit 1
fi

cleanup

echodebug "[DEBUG] Upload config response:"
echodebug "$(echo "$upload_config_resp" | jq '')"

url=$tfe_address/api/v2/workspaces/$workspace_id/runs
run_check_resp="$(tfe_api_call $url)"
if [ 0 -ne $? ]; then
    echoerr "Error getting runs to obtain status"
    exit 1
fi

echodebug "[DEBUG] Run check response:"
echodebug "$(echo "$run_check_resp" | jq '')"

run_id="$(echo "$run_check_resp" | jq -r '.data[] | select(.relationships."configuration-version".data.id == "'$config_id'") | .id')"
if [ 0 -ne $? ]; then
    echoerr "Error parsing API response for run ID"
    exit 1
fi

echo "Run $run_id submitted with configuration $config_id on $org/$workspace"

run_status=pending
lock_id=

while [ 0 != "$poll_run" ] &&
        ( [ pending = "$run_status"   ] ||
          [ planning = "$run_status"  ] ||
          [ applying = "$run_status"  ] ||
          [ confirmed = "$run_status" ] ); do
    # if the workspace was determined to be locked in the previous
    # poll, don't delay getting the final status and exiting.
    if [ true != "$workspace_locked" ]; then
        sleep $poll_run
    fi

    url=$tfe_address/api/v2/workspaces/$workspace_id/runs
    poll_run_resp=$(tfe_api_call $url)
    if [ 0 -ne $? ]; then
        echoerr "Error getting runs to obtain status"
        exit 1
    fi

    echodebug "[DEBUG] $poll_run_resp"

    run_status="$(echo "$poll_run_resp" | jq -r '.data[] | select(.id == "'$run_id'") | .attributes.status')"

    echo "$run_status"

    echodebug "[DEBUG] Requesting workspace info for $org/$workspace"

    url="$tfe_address/api/v2/organizations/$org/workspaces/$workspace"
    workspace_info_resp="$(tfe_api_call "$url")"
    if [ 0 -ne $? ]; then
        echoerr "Error requesting workspace info"
        exit 1
    fi

    echodebug "[DEBUG] Workspace info response:"
    echodebug "$(echo "$workspace_info_resp" | jq '')"

    workspace_locked="$(echo "$workspace_info_resp" | jq -r '.data.attributes.locked')"
    if [ 0 -ne $? ]; then
        echoerr "Error parsing API response for workspace lock status"
        exit 1
    fi

    if [ true = "$workspace_locked" ]; then
        lock_id="$(echo "$workspace_info_resp" | jq -r '.data.relationships."locked-by".data.id')"
        if [ 0 -ne $? ]; then
            echoerr "Error parsing API response for run locking workspace"
            cleanup
            exit 1
        fi

        if [ "$lock_id" != "$run_id" ]; then
            echoerr "Workspace is locked by $lock_id. Polling has been halted."
            exit 1
        fi

        # When the workspace is locked skip sleeping to quickly loop
        # around for the final run status.
        continue
    fi
done

