#!/bin/sh

## -------------------------------------------------------------------
##
## Copyright (c) 2018 HashiCorp. All Rights Reserved.
##
## This file is provided to you under the Mozilla Public License
## Version 2.0 (the "License"); you may not use this file
## except in compliance with the License.  You may obtain
## a copy of the License at
##
##   https://www.mozilla.org/en-US/MPL/2.0/
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
## -------------------------------------------------------------------

tfe_pushvars_description () (
    echo "Upload Terraform and/or environment variables to a TFE workspace"
)

tfe_pushvars_help () (
cat << EOF
SYNOPSIS
  tfe pushvars -name <ORGANIZATION>/<WORKSPACE> [OPTIONS] [CONFIG_DIR]

DESCRIPTION
  Update variables in a Terraform Enterprise workspace, using values from files
  or from the command line. By default, this command skips variables that
  already have a value in Terraform Enterprise; to replace existing values,
  use the '-overwrite <NAME>' option.

  If a config dir is specified, pushvars loads the terraform.tfvars and
  *.auto.tfvars files in that directory and adds them to the variables set on
  the command line. If the config dir is omitted, pushvars only uses variables
  from the command line.

OPTIONS
$(tfe_usage_args)

 -dry-run <BOOLEAN>   Show what would be done without changing any variables
                      in the workspace. Defaults to false.

 -var 'name=val'      Set a Terraform variable with a basic string value.

 -svar 'name=val'     Set a sensitive Terraform variable with a basic string
                      value.

 -hcl-var 'name=val'  Set a Terraform variable with an HCL value.

 -shcl-var 'name=val' Set a sensitive Terraform variable with an HCL value.

 -env-var 'name=val'  Set an environment variable.

 -senv-var 'name=val' Set a sensitive environment variable.

 -var-file <FILE>     Load Terraform variables from a tfvars file. Files can
                      only set non-sensitive variables.

 -overwrite <NAME>    Overwrite an existing value if the <NAME> variable is
                      already set in Terraform Enterprise. You must enable this
                      for every variable you want to overwrite. Can be
                      set multiple times.

 -hide-sensitive <BOOLEAN>
                      Whether to hide sensitive values in output. Defaults to
                      true.
NOTES
 All -var style args (except -var-file) can be set multiple times to operate
 on multiple variables with one command.

 If you specify a config directory to load variables from, it must be a
 directory where "terraform init" has been run.

 The curl and jq commands are required.

 The terraform command is required if operating on a tfvars file or a
 Terraform configuration.

EOF

# TODO options
#  -overwrite-all false Overwrite all variables with the variable values found
#                       in the configuration. Defaults to false. Use with
#                       extreme caution when operating with a config directory.
)

##
## Helper functions
##

# Replace quotes and newlines with escape characters to prepare the
# value for insertion into JSON.
escape_value () {
    echo "$1" | awk '
    {
        gsub(/"/,"\\\"")
    }
    NR == 1 {
        value_line = $0
    }
    NR != 1 {
        value_line = value_line "\\n" $0
    }
    END {
        printf "%s", value_line
    }'
}

make_var_create_payload () {
cat > "$payload" <<EOF
{
  "data": {
    "type":"vars",
    "attributes": {
      "key":"$1",
      "value":"$2",
      "category":"$3",
      "hcl":$4,
      "sensitive":$5
    }
  },
  "filter": {
    "organization": {
      "name":"$tfe_org"
    },
    "workspace": {
      "name":"$tfe_workspace"
    }
  }
}
EOF
}

make_var_update_payload () {
cat > "$payload" <<EOF
{
  "data": {
    "id":"$1",
    "attributes": {
      "key":"$2",
      "value":"$3",
      "category":"$4",
      "hcl":$5,
      "sensitive":$6
    },
    "type":"vars"
  }
}
EOF
}

# Given a list of variables followed by the properties all of those variables
# should have, either create or update them in TFE.
# $1 variables list
# $2 corresponding variable values list
# $3 variables type (terraform or env)
# $4 if the variables are hcl (true) or not (false)
# $5 if the variables are sensitive (true) or not (false)
process_vars () {
    # Bail out if the list is empty
    if [ -z "$1" ]; then
        return
    fi

    # Loop through the given variables. See if they are already in the
    # workspace. If so create them, else update them if they should be
    # updated.
    i=1
    for v in $1; do
        var_id="$(printf "%s" "$var_get_resp" | \
                     jq -r --arg var "$v" --arg type "$3" '.data[]
            | select(.attributes.category == $type)
            | select(.attributes.key == $var)
            | .id')"
        val="$(printf "%s" "$2" | awk -v i=$i 'NR==i{print;exit}')"
        if [ -z "$var_id" ]; then
            if [ "$hide_sensitive" = true ] && [ "$5" = true ]; then
                output_val=REDACTED
            else
                output_val="$val"
            fi

            printf "Creating %s type:%s hcl:%s sensitive:%s value:%s\n" "$v" "$3" "$4" "$5" "$output_val"

            if [ "$dry_run" != true ]; then
                url="$tfe_address/api/v2/vars"
                make_var_create_payload "$v" "$val" $3 "$4" "$5"
                if [ 0 -ne $? ]; then
                    echoerr "Error generating payload file for $v"
                    i=$(($i + 1))
                    continue
                fi

                echodebug "[DEBUG] API request for variable create:"
                if ! var_create_resp="$(tfe_api_call -d @"$payload" "$url")"; then
                    echoerr "Error creating variable $v"
                fi

                cleanup "$payload"
            fi
        else
            # This existing variable should only be overwritten if it was
            # specified with -overwrite NAME
            if echo "$overwrites" | grep -E "^$v$" >/dev/null 2>&1; then
                if [ "$hide_sensitive" = true ] && [ "$5" = true ]; then
                    output_val=REDACTED
                else
                    output_val="$val"
                fi

                printf "Updating %s type:%s hcl:%s sensitive:%s value:%s\n" "$v" "$3" "$4" "$5" "$output_val"

                if [ "$dry_run" != true ]; then
                    url="$tfe_address/api/v2/vars/$var_id"
                    make_var_update_payload "$var_id" "$v" "$val" "$3" "$4" "$5"
                    if [ 0 -ne $? ]; then
                        echoerr "Error generating payload file for $v"
                        i=$(($i + 1))
                        continue
                    fi

                    echodebug "[DEBUG] API request for variable update:"
                    if ! var_update_resp="$(tfe_api_call --request PATCH -d @"$payload" "$url")"; then
                        echoerr "Error updating variable $v"
                    fi

                    cleanup "$payload"
                fi
            fi
        fi
        i=$(($i + 1))
    done
}

tfe_pushvars () (
    payload="$TMPDIR/tfe-push-vars-payload-$(date +%s)"
    dry_run=false
    config_dir=
    var_file=
    var_file_arg=
    overwrites=
    hide_sensitive=true

    vars=
    vars_values=
    svars=
    svars_values=
    hclvars=
    hclvars_values=
    shclvars=
    shclvars_values=
    envvars=
    envvars_values=
    sensvars=
    sensvars_values=
    defaultvars=
    defaultvars_values=
    defaulthclvars=
    defaulthclvars_values=

    # Check for required standard options
    if ! check_required; then
        return 1
    fi

    # Parse options

    while [ -n "$1" ]; do
        # If this is a common option it has already been parsed. Skip it and
        # its value.
        if is_common_opt "$1"; then
            shift
            shift
            continue
        fi

        case "$1" in
            -dry-run)
                case "$2" in
                    true)
                        dry_run=true
                        ;;
                    false)
                        dry_run=false
                        ;;
                    *)
                        echoerr "-dry-run should be true or false"
                        return 1
                        ;;
                esac
                ;;
            -overwrite)
                new_overwrite="$(assign_arg "$1" "$2")"
                overwrites="$(append "$overwrites" "$new_overwrite")"
                ;;
            #-overwrite-all)
            #    ;;
            -var)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value=${new_var_arg#*=}
                vars="$(append "$vars" "$new_var_name")"
                vars_values="$(append "$vars_values" "$new_var_value")"
                ;;
            -svar)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value=${new_var_arg#*=}
                svars="$(append "$svars" "$new_var_name")"
                svars_values="$(append "$svars_values" "$new_var_value")"
                ;;
            -hcl-var)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value="$(escape_value "${new_var_arg#*=}")"
                hclvars="$(append "$hclvars" "$new_var_name")"
                hclvars_values="$(append "$hclvars_values" "$new_var_value")"
                ;;
            -shcl-var)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value="$(escape_value "${new_var_arg#*=}")"
                shclvars="$(append "$shclvars" "$new_var_name")"
                shclvars_values="$(append "$shclvars_values" "$new_var_value")"
                ;;
            -env-var)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value=${new_var_arg#*=}
                envvars="$(append "$envvars" "$new_var_name")"
                envvars_values="$(append "$envvars_values" "$new_var_value")"
                ;;
            -senv-var)
                new_var_arg="$(assign_arg "$1" "$2")"
                new_var_name=${new_var_arg%%=*}
                new_var_value=${new_var_arg#*=}
                senvvars="$(append "$senvvars" "$new_var_name")"
                senvvars_values="$(append "$senvvars_values" "$new_var_value")"
                ;;
            -var-file)
                var_file="$(assign_arg "$1" "$2")"
                var_file_arg="-var-file=$var_file"
                ;;
            -hide-sensitive)
                case "$2" in
                    true)
                        hide_sensitive=true
                        ;;
                    false)
                        hide_sensitive=false
                        ;;
                    *)
                        echoerr "-hide-sensitive should be true or false"
                        return 1
                        ;;
                esac
                ;;
            *)
                # Shouldn't get here until the last option, the optional
                # config directory
                if [ $# -gt 1 ]; then
                    echoerr "Trailing options following config directory $1"
                    return 1
                fi

                config_dir="$1"
                ;;
        esac
        [ -n "$1" ] && shift
        [ -n "$1" ] && shift
    done

    if [ -n "$config_dir" ] || [ -n "$var_file" ]; then
        tf_version_required 0 11 6
    fi

    # Get the variable listing for the workspace
    url="$tfe_address/api/v2/vars?filter%5Borganization%5D%5Bname%5D=$tfe_org&filter%5Bworkspace%5D%5Bname%5D=$tfe_workspace"

    echodebug "[DEBUG] API list variables URL:"
    echodebug "$url"

    echodebug "[DEBUG] API request for variable list:"
    if ! var_get_resp="$(tfe_api_call $url)"; then
        echoerr "Error listing variables"
        return 1
    fi

    # If a config directory was given, then variables with defaults in
    # the configuration need to be discovered.
    if [ -n "$config_dir" ]; then
        cd "$config_dir"
        if [ 0 -ne $? ]; then
            echoerr "Error entering the config directory:"
            echoerr "$config_dir"
            return 1
        fi

        # Get all of the variables from all of the .tf files
        # Outputs:
        #   TYPE NAME
        # e.g.
        #   hcl my_var
        all_vars="$(awk '
            BEGIN {
                VARS="\"[-_a-zA-Z0-9]*\""
                in_var = 0
                in_value = 0
                in_default = 0
                in_comment = 0
                in_heredoc = 0
                heredoc_id = ""
                in_map = 0
                in_default_block = 0
                seen_variable = 0
            }
            /^[ \t\r\n\v\f]*#/ {
                # line starts with a comment
                next
            }
            /\/\*/ {
                # entering a comment block
                in_comment = 1
            }
            in_comment == 1 && /\*\// {
                # exiting a comment block
                in_comment = 0
                next
            }
            in_comment == 1 {
                # still in a comment block
                next
            }
            in_map == 1 && $0 !~ /}/ {
                # in a map and do not see a "}" to close it
                next
            }
            in_map == 1 && /}/ {
                # in a map and see a "}" to close it.
                # assuming that a variable identifier is not going to follow
                # the "}" on the same line, which could be a bad assumption
                # but also really awful formatting
                in_map = 0
                next
            }
            /variable/ && seen_variable == 0 {
                # the variable keyword
                seen_variable = 1
            }
            $0 ~ VARS && seen_variable == 1 {
                # get the variable name
                in_var = 1
                match($0, /\"[a-zA-Z0-9]/)
                l=RLENGTH
                match($0, VARS)
                name = substr($0, RSTART+1, RLENGTH-l)
                seen_variable = 0
            }
            in_heredoc == 1 && $0 !~ "^" heredoc_id "$" {
                # in a heredoc and have not seen the id to end it
                next
            }
            in_heredoc == 1 && $0 ~ "^" heredoc_id "$" {
                # exiting a heredoc
                in_heredoc = 0
                heredoc_id = ""
                next
            }
            in_var == 1 && /{/ {
                # entered the variable block to look for default
                in_var_block = 1
            }
            in_var_block == 1 && /default/ {
                # this variable has a default
                in_default = 1
            }
            in_var_block == 1 && in_default == 0 && in_value == 0 && /}/ {
                # Variable block with no default. Its value may come from
                # a tfvars file loaded later.
                in_var = 0
                in_var_block = 0
                in_default = 0
                in_default_block = 0
                in_value = 0
                next
            }
            in_default == 1 && /=/{
                # entering the RHS of default =
                in_value = 1
            }
            in_var == 1 && in_default == 1 && in_value == 1 && /["{<\[]/ {
                # inside the RHS and found something that looks like a value.
                # determine the variable type (hcl, non-hcl).
                # match all the things that are not Terraform variable values
                m = match($0, /[^"{<\[]*/)
                if(m != 0) {
                    # Get the first character after all of the things that are not
                    # Terraform variable values
                    value_char = substr($0, RLENGTH + 1, 1)

                    if(value_char == "{") {
                        # this is a map. if it is not all on one line then
                        # we are in a map
                        if(match($0, /}/) == 0){
                            in_map = 1
                        }
                    } else {
                        if(value_char == "<") {
                            # entering a heredoc. valid anchors should be directly
                            # next to the brackets
                            in_heredoc = 1
                            match($0, /<<[-_a-zA-Z0-9]+/)
                            heredoc_id = substr($0, RSTART+2, RLENGTH-2)
                        }
                    }
                    # not in a map, so this is a variable name
                    print name
                    in_var = 0
                    in_value = 0
                    in_var_block = 0
                    in_default = 0
                    in_default_block = 0
                }
            } ' *.tf)"
    elif [ -n "$var_file" ]; then
        # Going to locate all of the variables from a tfvars file.
        # Will get the values by using the tfvars file and creating a
        # temporary config with just variable names in it for use with
        # the terraform console command.
        tfvar_dir="$TMPDIR/tfe-push-vars-$(date +%s)"
        mkdir "$tfvar_dir"
        if [ 0 -ne $? ]; then
            echoerr "Error creating temporary directory for tfvars."
            return 1
        fi

        echodebug "[DEBUG] Temporary tfvars dir:"
        echodebug "$tfvar_dir"

        cp "$var_file" "$tfvar_dir"
        if [ 0 -ne $? ]; then
            echoerr "Error copying variable file to temporary path."
            return 1
        fi

        cd "$tfvar_dir"
        if [ 0 -ne $? ]; then
            echoerr "Error entering variable file temporary path."
            return 1
        fi

        # This is not a great "parser" but it hopefully overreaches on finding
        # variable names, then we can silently ignore errors from terraform
        # console (output when TF_LOG=1).

        # Outputs:
        #   TYPE NAME
        # e.g.
        #   hcl my_var
        all_vars="$(awk '
            BEGIN {
                in_var = 0
                in_value = 0
                in_comment = 0
                in_heredoc = 0
                heredoc_id = ""
                in_map = 0
            }
            /^[ \t\r\n\v\f]*#/ {
                # line starts with a comment
                next
            }
            /\/\*/ {
                # entering a comment block
                in_comment = 1
                next
            }
            in_comment == 1 && /\*\// {
                # exiting a comment block
                in_comment = 0
                next
            }
            in_comment == 1 {
                # still in a comment block
                next
            }
            in_map == 1 && $0 !~ /}/ {
                # in a map and do not see a "}" to close it
                next
            }
            in_map == 1 && /}/ {
                # in a map and see a "}" to close it.
                # assuming that a variable identifier is not going to follow
                # the "}" on the same line, which could be a bad assumption
                # but also really awful formatting
                in_map = 0
                next
            }
            in_heredoc == 1 && $0 !~ "^" heredoc_id "$" {
                # in a heredoc and have not seen the id to end it
                next
            }
            in_heredoc == 1 && $0 ~ "^" heredoc_id "$" {
                # exiting a heredoc
                in_heredoc = 0
                heredoc_id = ""
                next
            }
            /^[ \t\r\n\v\f]*[a-zA-Z0-9]/ && in_var == 0 && $0 !~ /,$/ {
                # token text, not in a variable already, does not end in ",".
                # this looks like a variable name
                in_var = 1
                match($0, /[-_a-zA-Z0-9]+/)
                name = substr($0, RSTART, RLENGTH)

                # remove the potential variable name from $0 so a search
                # for "=" can continue on this line as well as subsequent lines
                sub(name, "")
            }
            in_var == 1 && /^[ \t\r\n\v\f]+[^=]/ {
                # have a potential variable name but the next thing seen
                # is not "=", so this is not a variable name.
                in_var = 0
                next
            }
            in_var == 1 && /^[ \t\r\n\v\f]*=/ {
                # have a variable name and the next thing seen is =
                in_value = 1
            }
            in_var == 1 && in_value == 1 && /["{<\[]/ {
                # see if we are entering a map or heredoc so we can skip those
                # sections.
                # match all the things that are not Terraform variable values.
                m = match($0, /[^"{<\[]*/)
                if(m != 0) {
                    # Get the first character after all of the things that are not
                    # Terraform variable values
                    value_char = substr($0, RLENGTH + 1, 1)

                    if(value_char == "{") {
                        # this is a map. if it is not all on one line then
                        # we are in a map
                        if(match($0, /}/) == 0){
                            in_map = 1
                        }
                    } else {
                        if(value_char == "<") {
                            # entering a heredoc. valid anchors should be directly
                            # next to the brackets
                            in_heredoc = 1
                            match($0, /<<[-_a-zA-Z0-9]+/)
                            heredoc_id = substr($0, RSTART+2, RLENGTH-2)
                        }
                    }
                    # not in a map, so this is a variable name
                    print name
                    printf "variable \"%s\" {}\n", name >> "vars.tf"
                    in_var = 0
                    in_value = 0
                }
            }' "$(basename "$var_file")")"

            echodebug "[DEBUG] Temporary directory contents:"
            echodebug "$(ls)"

            echodebug "[DEBUG] Temporary file contents:"
            echodebug "$(cat *)"
    fi

    echodebug "[DEBUG] All variables:"
    echodebug "$all_vars"

    # All of the 'parsed' variable names are just candidates, as they may
    # not have defaults or may not be variable names at all (e.g. map
    # assignments). Loop through the potential variables and get their
    # values, then determine if they are HCL or not.

    if [ -n "$all_vars" ]; then
        for var in $all_vars; do
            if [ -z "$var_file_arg" ]; then
                val_lines="$(echo "var.$var" | terraform console 2>&3)"
            else
                val_lines="$(echo "var.$var" | terraform console "$var_file_arg" 2>&3)"
            fi

            if [ 0 -ne $? ]; then
                echodebug "Unable to retrieve value for potential variable $var"
                echodebug "Stdout of terraform console was:"
                echodebug "$val_lines"
                continue
            fi
            val="$(escape_value "$val_lines")"

            # Inspect the first character of the value to see if it is a
            # list or map
            first="$(echo "$val" | cut -c 1-1 | head -1)"
            if [ "$first" = "{" ] || [ "$first" = "[" ]; then
                defaulthclvars="$(append "$defaulthclvars" "$var")"
                defaulthclvars_values="$(append "$defaulthclvars_values" "$val")"
            else
                defaultvars="$(append "$defaultvars" "$var")"
                defaultvars_values="$(append "$defaultvars_values" "$val")"
            fi
        done
    fi

    # Send each list of the different types of variables through to be created
    # or updated, along with the properties that that list should abide by.

    # Note that the lists are sent with the end-of-list marker removed, which
    # was added by the append function.

    #            variable list,        value list,                  type,     hcl,  sensitive
    process_vars "${defaultvars%.}"    "${defaultvars_values%.}"    terraform false false
    process_vars "${defaulthclvars%.}" "${defaulthclvars_values%.}" terraform true  false
    process_vars "${vars%.}"           "${vars_values%.}"           terraform false false
    process_vars "${hclvars%.}"        "${hclvars_values%.}"        terraform true  false
    process_vars "${svars%.}"          "${svars_values%.}"          terraform false true
    process_vars "${shclvars%.}"       "${shclvars_values%.}"       terraform true  true
    process_vars "${envvars%.}"        "${envvars_values%.}"        env       false false
    process_vars "${senvvars%.}"       "${senvvars_values%.}"       env       false true
)
