#!/bin/sh

. ../utils

# tfh by itself should return 1 and contain certain text
output="$(tfh 2>&1)"
assert_equal "tfh_ret_1" 1 $?
assert_contains "tfh_has_synopsis" "SYNOPSIS" "$output"
assert_contains "tfh_has_description" "DESCRIPTION" "$output"
assert_contains "tfh_has_help_describe" " help" "$(echo "$output" | awk 'NR>6')"

# tfh help pushconfig should return 0 and contain the tfh pushconfig synopsis
pushconfig_output="$(tfh help pushconfig 2>&1)"
assert_equal "tfh_help_pushconfig_ret_0" 0 $?
assert_contains "tfh_help_pushconfig_has_synopsis" "tfh pushconfig -- " "$pushconfig_output"

