#!/bin/sh

## -------------------------------------------------------------------
##
## Copyright (c) 2018 HashiCorp. All Rights Reserved.
##
## This file is provided to you under the Mozilla Public License
## Version 2.0 (the "License"); you may not use this file
## except in compliance with the License.  You may obtain
## a copy of the License at
##
##   https://www.mozilla.org/en-US/MPL/2.0/
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
## -------------------------------------------------------------------

tfe_show_description () (
    echo "Show Terraform Enterprise workspace details"
)

tfe_show_help () (
# Be sure to include the common options with tfe_usage_args
cat << EOF
SYNOPSIS
 tfe workspace show -name <ORGANIZATION>/<WORKSPACE> [OPTIONS]

DESCRIPTION
 Show Terraform Enterprise workspace details.

OPTIONS
$(tfe_usage_args)

NOTES
 The curl and jq commands are required.

EOF
)

tfe_show () (
    # Ensure all of tfe_org, etc, are set. Workspace is not required.
    if ! check_required tfe_org tfe_token tfe_address; then
        return 1
    fi

    echodebug "[DEBUG] API request to show workspace:"
    url="$tfe_address/api/v2/organizations/$tfe_org/workspaces/$tfe_workspace"
    if ! show_resp="$(tfe_api_call "$url")"; then
        echoerr "Error showing workspace information for $tfe_workspace"
        return 1
    fi

    printf "%s" "$show_resp" | jq -r '
        "name              = " + .data.attributes.name,
        "id                = " + .data.id,
        "auto-apply        = " + (.data.attributes."auto-apply"|tostring),
        "locked            = " + (.data.attributes.locked|tostring),
        "created-at        = " + .data.attributes."created-at",
        "working-directory = " + .data.attributes."working-directory",
        "terraform-version = " + .data.attributes."terraform-version"'
)
